// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp71Nh_gQPh-Xr6njqIRl1YKjGc4aOXWY',
    appId: '1:920632069583:web:de6c37c1c2b2b8c49e56ba',
    messagingSenderId: '920632069583',
    projectId: 'top-movies-c15de',
    authDomain: 'top-movies-c15de.firebaseapp.com',
    storageBucket: 'top-movies-c15de.appspot.com',
    measurementId: 'G-7H7F2W4Q4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCepC02vLniJuDEeXfCpRPUUScPj6Otgrw',
    appId: '1:920632069583:android:43e7901b8870913e9e56ba',
    messagingSenderId: '920632069583',
    projectId: 'top-movies-c15de',
    storageBucket: 'top-movies-c15de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYhVHq4cVD1uH4ZFBGBmeEvoVi55X7ecw',
    appId: '1:920632069583:ios:41370f8ff03695329e56ba',
    messagingSenderId: '920632069583',
    projectId: 'top-movies-c15de',
    storageBucket: 'top-movies-c15de.appspot.com',
    iosBundleId: 'com.example.topMovies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYhVHq4cVD1uH4ZFBGBmeEvoVi55X7ecw',
    appId: '1:920632069583:ios:41370f8ff03695329e56ba',
    messagingSenderId: '920632069583',
    projectId: 'top-movies-c15de',
    storageBucket: 'top-movies-c15de.appspot.com',
    iosBundleId: 'com.example.topMovies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp71Nh_gQPh-Xr6njqIRl1YKjGc4aOXWY',
    appId: '1:920632069583:web:abd07b2fb2adf2729e56ba',
    messagingSenderId: '920632069583',
    projectId: 'top-movies-c15de',
    authDomain: 'top-movies-c15de.firebaseapp.com',
    storageBucket: 'top-movies-c15de.appspot.com',
    measurementId: 'G-9LY8R70V0V',
  );
}
